### ISSUE TITLE
ssr的情况下，不能用，不知道为什么要用windows

### ISSUE THREAD

**Issue by jjskay** [warpcgd/vue-concise-slider#21]
Nuxt.js Error:

ReferenceError: window is not defined
    at 7.server-bundle.js:231:3043
    at 7.server-bundle.js:231:2975
    at t.exports (~/vue-concise-slider/dist/module.js:1:3257)
    at Object.<anonymous> (~/vue-concise-slider/dist/module.js:1:4112)
    at i (~/vue-concise-slider/dist/module.js:1:360)
    at Object.<anonymous> (~/vue-concise-slider/dist/module.js:1:3741)
    at i (~/vue-concise-slider/dist/module.js:1:360)
    at Object.t.exports.t (~/vue-concise-slider/dist/module.js:1:595)
    at i (~/vue-concise-slider/dist/module.js:1:360)
    at t.__esModule.default (~/vue-concise-slider/dist/module.js:1:433)

**Comment by warpcgd** [comment]
ssr？我查看了代码，发现没用到window呢
